export const loseMessages = [
    "You Lose 😈",
    "Too slow, human 🧠💨",
    "Try harder next time!",
    "Beep Boop... you lost 🤖",
    "I'm always one step ahead 👣",
    "Crushed you like a bug 🪳",
    "Your reflexes are... cute 😏",
    "Was that even a try?",
    "You're making this too easy!",
    "Just give up already 😆",
    "You vs Me? No contest 😎",
    "I see all, I know all 🔮",
    "You blinked, I won 😜",
    "You're predictable, bro 😴",
    "Nice move... not!",
    "Did your grandma teach you that?",
    "Better luck in your next life!",
    "I eat humans for breakfast ☕",
    "Your fingers betrayed you 🖕",
    "That was adorable 😹",
    "Oops, I did it again 🎶",
    "You call that strategy?",
    "You should retire 🤷‍♂️",
    "Legend says... you're still losing!",
    "That was... brave. But nope.",
    "Not today, meatbag 🧠",
    "Another one bites the dust 💥",
    "I'm basically psychic 🔮",
    "You vs AI? Classic mistake.",
    "A valiant effort. Still lost.",
    "Resistance is futile.",
];
