import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/ui/Navbar'
import {BackgroundBoxesDemo} from "@/app/components/ui/TestBackgroundBoxes";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Realashrafi",
    description: "Generated by "+"https://github.com/realashrafi",
    manifest:"/manifest.json"
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${inter.className} bg-[#010517]`}>
        <Navbar/>
        {children}
        <BackgroundBoxesDemo/>
        </body>
        </html>
    );
}
