import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/ui/Navbar';
import MindARGlobalLoader from "@/app/real_fusion/components/MindARGlobalLoader";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Realashrafi",
    description: "Generated by https://github.com/realashrafi",
    manifest: "/manifest.json",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <MindARGlobalLoader />
        </head>
        <body className={`${inter.className} bg-[#010517]`}>
        <Navbar />
        {children}
        </body>
        </html>
    );
}