import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from '@/app/components/ui/Navbar'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Realashrafi",
    description: "Generated by "+"https://github.com/realashrafi",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Navbar/>
        {children}
        </body>
        </html>
    );
}
